
services:
  postgres:
    image: postgres:13
    container_name: airflow-postgres-13
    ports:
      - 5434:5432
    environment:
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_USER=airflow
      - POSTGRES_DB=airflow
    networks:
      - airflow_network
    volumes:
      - postgres-db-volume-13:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always

networks:
  airflow_network:
    name: airflow_network
    driver: bridge

volumes:
  postgres-db-volume-13: